FROM python:3.13.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /code
ENV PATH="/code/.venv/bin:$PATH"

COPY pyproject.toml .python-version uv.lock scripts/ingest_green_taxi_data.py ./
RUN uv sync --locked

COPY data/green_tripdata_2025-11.parquet ./data/

ENTRYPOINT ["uv", "run", "ingest_green_taxi_data.py"]