FROM python:3.13.11-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/

WORKDIR /code
ENV PATH="/code/.venv/bin:$PATH"

COPY pyproject.toml .python-version uv.lock scripts/ingest_zones_data.py ./
RUN uv sync --locked

COPY data/taxi_zone_lookup.csv ./data/

ENTRYPOINT ["uv", "run", "ingest_zones_data.py"]